version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      cache_from:
        - type=gha
      cache_to:
        - type=gha,mode=max
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      LOG_LEVEL: debug
    volumes:
      - .:/var/www/html:cached
      - /var/www/html/node_modules
      - /var/www/html/vendor

  db:
    ports:
      - "3306:3306"

  redis:
    ports:
      - "6379:6379"
