; App-oriented defaults
memory_limit=512M
upload_max_filesize=50M
post_max_size=50M
max_execution_time=120

; Opcache
opcache.enable=1
opcache.enable_cli=1
opcache.jit=0
opcache.memory_consumption=128
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=20000
opcache.validate_timestamps=0
