name: CI/CD Pipeline Esaturasi

on:
  push:
    branches: [ "main" ] # Berjalan otomatis ketika kamu push ke branch main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Langkah Unit Test (Poin 19 & 20)
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, ctype, iconv, pdo-mysql

      - name: Install Dependencies
        run: composer install # Buat vendor sementara di GitHub runner untuk testing

      - name: Copy .env
        run: cp .env.example .env && php artisan key:generate

      - name: Run Unit Tests
        run: php artisan test --coverage-text # Menampilkan hasil actual vs expected & coverage

      # Langkah Build dan Push ke Docker Hub (Poin 9, 10, 16)
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/esaturasi:latest # format username/nama-image

  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
      # Langkah Deploy via SSH Remote Appleboy (Poin 18)
      - name: SSH Remote Deployment to VPS JTI
        uses: appleboy/ssh-action@master
        with:
          host: 103.157.27.203
          username: Kelompok3
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /home/Kelompok3/esaturasi-deploy
            docker compose pull
            docker compose up -d